CREATE TABLE (
  "Idea" TITLE,
  "Origin" SELECT('AI':gray, 'Human':pink),
  "Verdict" FORMULA('if(((((((min(5, (((prop("SOM (users/mo)") * if(prop("Impact") == "Minimal (1)", 1, if(prop("Impact") == "Significant (2)", 2, if(prop("Impact") == "Transformative (3)", 3, 0)))) * prop("Confidence (/1.0)")) / if(prop("Effort (weeks)") == 0, 1, prop("Effort (weeks)"))) / 2000) * 0.35) + (prop("Moat (/5)") * 0.1)) + (prop("Unfair Advantage (/5)") * 0.1)) + (prop("Revenue Potential (/5)") * 0.2)) + (prop("Competitive Window (/5)") * 0.15)) + (max(0, 5 - (prop("Time to $10k (months)") / 6)) * 0.1)) >= 4, "🔥 Strong Go", if(((((((min(5, (((prop("SOM (users/mo)") * if(prop("Impact") == "Minimal (1)", 1, if(prop("Impact") == "Significant (2)", 2, if(prop("Impact") == "Transformative (3)", 3, 0)))) * prop("Confidence (/1.0)")) / if(prop("Effort (weeks)") == 0, 1, prop("Effort (weeks)"))) / 2000) * 0.35) + (prop("Moat (/5)") * 0.1)) + (prop("Unfair Advantage (/5)") * 0.1)) + (prop("Revenue Potential (/5)") * 0.2)) + (prop("Competitive Window (/5)") * 0.15)) + (max(0, 5 - (prop("Time to $10k (months)") / 6)) * 0.1)) >= 3.5, "🟢 High Conviction", if(((((((min(5, (((prop("SOM (users/mo)") * if(prop("Impact") == "Minimal (1)", 1, if(prop("Impact") == "Significant (2)", 2, if(prop("Impact") == "Transformative (3)", 3, 0)))) * prop("Confidence (/1.0)")) / if(prop("Effort (weeks)") == 0, 1, prop("Effort (weeks)"))) / 2000) * 0.35) + (prop("Moat (/5)") * 0.1)) + (prop("Unfair Advantage (/5)") * 0.1)) + (prop("Revenue Potential (/5)") * 0.2)) + (prop("Competitive Window (/5)") * 0.15)) + (max(0, 5 - (prop("Time to $10k (months)") / 6)) * 0.1)) >= 3, "✅ Side Bet", if(((((((min(5, (((prop("SOM (users/mo)") * if(prop("Impact") == "Minimal (1)", 1, if(prop("Impact") == "Significant (2)", 2, if(prop("Impact") == "Transformative (3)", 3, 0)))) * prop("Confidence (/1.0)")) / if(prop("Effort (weeks)") == 0, 1, prop("Effort (weeks)"))) / 2000) * 0.35) + (prop("Moat (/5)") * 0.1)) + (prop("Unfair Advantage (/5)") * 0.1)) + (prop("Revenue Potential (/5)") * 0.2)) + (prop("Competitive Window (/5)") * 0.15)) + (max(0, 5 - (prop("Time to $10k (months)") / 6)) * 0.1)) >= 2.5, "🔶 Conditional Go", if(((((((min(5, (((prop("SOM (users/mo)") * if(prop("Impact") == "Minimal (1)", 1, if(prop("Impact") == "Significant (2)", 2, if(prop("Impact") == "Transformative (3)", 3, 0)))) * prop("Confidence (/1.0)")) / if(prop("Effort (weeks)") == 0, 1, prop("Effort (weeks)"))) / 2000) * 0.35) + (prop("Moat (/5)") * 0.1)) + (prop("Unfair Advantage (/5)") * 0.1)) + (prop("Revenue Potential (/5)") * 0.2)) + (prop("Competitive Window (/5)") * 0.15)) + (max(0, 5 - (prop("Time to $10k (months)") / 6)) * 0.1)) >= 2, "🟡 Weak Maybe", "🚫 Hard No")))))'),
  "Opportunity Score (/5)" FORMULA('round(((((((min(5, (((prop("SOM (users/mo)") * if(prop("Impact") == "Transformative (3)", 3, if(prop("Impact") == "Significant (2)", 2, 1))) * prop("Confidence (/1.0)")) / prop("Effort (weeks)")) / 2000) * 0.35) + (prop("Moat (/5)") * 0.1)) + (prop("Unfair Advantage (/5)") * 0.1)) + (prop("Revenue Potential (/5)") * 0.2)) + (prop("Competitive Window (/5)") * 0.15)) + (max(0, 5 - (prop("Time to $10k (months)") / 6)) * 0.1)) * 100) / 100'),
  "Category" SELECT('SaaS':blue, 'Marketplace':purple, 'Content':yellow, 'Tool':green, 'Service':orange),
  "RICE Score" FORMULA('((prop("SOM (users/mo)") * if(prop("Impact") == "Transformative (3)", 3, if(prop("Impact") == "Significant (2)", 2, if(prop("Impact") == "Minimal (1)", 1, 0)))) * prop("Confidence (/1.0)")) / max(prop("Effort (weeks)"), 1)'),
  "Time to $10k (months)" NUMBER,
  "Status" SELECT('💡 New':yellow, '🔍 Researching':blue, '✅ Evaluated':green, '🚀 In Progress':purple, '❌ Killed':red),
  "Impact" SELECT('Minimal (1)':gray, 'Significant (2)':orange, 'Transformative (3)':green),
  "Confidence (/1.0)" NUMBER,
  "Effort (weeks)" NUMBER,
  "Moat (/5)" NUMBER,
  "Unfair Advantage (/5)" NUMBER,
  "Revenue Potential (/5)" NUMBER,
  "Competitive Window (/5)" NUMBER,
  "SOM (users/mo)" NUMBER,
  "Date Added" DATE,
  "SAM" NUMBER,
  "TAM" NUMBER
)
